name: flight_tickets
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
   - family: Oxygen-Bold
     fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Regular.ttf


